Repository SU-SWS/stanford_news, pull requests merged in 2020-09, with the labels that each got.

#98 D8CORE-2675: removing the external link arrow from social media icons
  dist/css/news-node.css
  lib/scss/components/news-node/_news-node.scss
Labels: frontend, size/xs

#99 8.x-2.x > 8.2.5
  CHANGELOG.md
  composer.json
  dist/css/news-node.css
  lib/scss/components/news-node/_news-node.scss
  stanford_news.info.yml
Labels: frontend, patch, size/xs

#100 D8CORE-2548: change the pagination counts
  config/install/views.view.stanford_news.yml
Labels: size/xs
