Repository SU-SWS/stanford_news, pull requests merged in 2020-05, with the labels that each got.

#69 D8 core 1900: News byline fixes
  dist/css/news-node.css
  lib/scss/components/news-node/_news-node.scss
  templates/sections/news-byline-social.html.twig
Labels: size/xs

#70 D8 core 2052 - Visual QA edits
  dist/css/news-list-item.css
  dist/css/news-node.css
  dist/css/news-vertical-teaser.css
  lib/scss/components/news-list-item/_list-item.scss
  lib/scss/components/news-node/_news-node.scss
  lib/scss/components/news-vertical-teaser/_news-vertical-teaser.scss
Labels: size/xs

#68 News accelerant tests
  .circleci/config.yml
  composer.json
  config/install/core.entity_form_display.node.stanford_news.default.yml
  config/install/core.entity_view_display.node.stanford_news.default.yml
  config/install/field.field.node.stanford_news.layout_selection.yml
  config/install/field.field.node.stanford_news.su_news_banner.yml
  config/install/field.field.node.stanford_news.su_news_byline.yml
  config/install/field.field.node.stanford_news.su_news_dek.yml
  config/install/field.field.node.stanford_news.su_news_featured_media.yml
  config/install/field.field.node.stanford_news.su_news_publishing_date.yml
  config/install/field.field.node.stanford_news.su_news_source.yml
  config/install/field.field.paragraph.news_views.su_news_view_field.yml
  config/install/field.storage.node.layout_builder__layout.yml
  config/install/page_manager.page_variant.stanford_news_list_terms-layout_builder-0.yml
  config/install/paragraphs.paragraphs_type.news_views.yml
  config/install/views.view.stanford_news.yml
  src/Plugin/Block/SignupBlock.php
  stanford_news.info.yml
  stanford_news.install
  stanford_news.module
  templates/block/signup-block.html.twig
  tests/codeception/acceptance/NewsNodeCest.php
  tests/src/Unit/Plugin/Block/SignupBlockTest.php
Labels: backend, ci, frontend, patch, size/m, tests

#72 Update page_manager.page.stanford_news_list_terms.yml
  config/install/page_manager.page.stanford_news_list_terms.yml
Labels: size/xs

#73 D8CORE-000: Limit options in viewfield react.
  stanford_news.module
Labels: backend, size/xs

#74 added xmlsitemap and metatag configs for optional
  README.md
  config/install/core.base_field_override.node.stanford_news.promote.yml
  config/optional/metatag.metatag_defaults.node__stanford_news.yml
  config/optional/metatag.metatag_defaults.page_variant__stanford_news_list-layout_builder-0.yml
  config/optional/metatag.metatag_defaults.page_variant__stanford_news_list_terms-layout_builder-0.yml
  config/optional/xmlsitemap.settings.node.stanford_news.yml
  config/optional/xmlsitemap.settings.taxonomy_term.stanford_news_topics.yml
Labels: size/xs

#75 D8CORE-000: Fixes broken filtering logic on view field.
  stanford_news.module
Labels: backend, size/xs

#76 8.2.0
  CHANGELOG.md
  composer.json
  stanford_news.info.yml
Labels: patch, size/xs

#77 back to dev
  stanford_news.info.yml
Labels: size/xs

#78 D8CORE-2110: Removed news views paragraph type.
  composer.json
  config/install/core.entity_form_display.paragraph.news_views.default.yml
  config/install/core.entity_view_display.paragraph.news_views.default.yml
  config/install/field.field.paragraph.news_views.su_news_view_field.yml
  config/install/field.storage.paragraph.su_news_view_field.yml
  config/install/paragraphs.paragraphs_type.news_views.yml
  stanford_news.info.yml
  stanford_news.module
Labels: backend, patch, size/s

#79 D8CORE-000: Changed headline field to 180 characters.
  config/install/field.field.node.stanford_news.su_news_headline.yml
  config/install/field.storage.node.su_news_headline.yml
Labels: size/xs

#81 "8.x-2.x > 8.2.1
  CHANGELOG.md
  composer.json
  config/install/core.entity_form_display.paragraph.news_views.default.yml
  config/install/core.entity_view_display.paragraph.news_views.default.yml
  config/install/field.field.node.stanford_news.su_news_headline.yml
  config/install/field.field.paragraph.news_views.su_news_view_field.yml
  config/install/field.storage.node.su_news_headline.yml
  config/install/field.storage.paragraph.su_news_view_field.yml
  config/install/paragraphs.paragraphs_type.news_views.yml
  stanford_news.info.yml
  stanford_news.module
Labels: backend, patch, size/s

#82 D8CORE-1958: changing a span to a div for validation fix
  templates/sections/news-byline-social.html.twig
Labels: frontend, size/xs
