Repository SU-SWS/stanford_news, pull requests merged in 2020-06, with the labels that each got.

#84 Rabbit home?
  stanford_news.info.yml
Labels: patch, size/xs

#85 8.x-2.x > 8.2.2
  CHANGELOG.md
  src/Plugin/Block/SignupBlock.php
  stanford_news.info.yml
  templates/sections/news-byline-social.html.twig
Labels: backend, frontend, patch, size/xs

#87 D8CORE-2292: Added in the More news button
  config/install/views.view.stanford_news.yml
  dist/css/news-vertical-teaser.css
  lib/scss/components/news-vertical-teaser/_news-vertical-teaser.scss
Labels: frontend, size/xs

#88 D8CORE-2070: changing the MS on the header for accelerants.
  dist/css/news-list-item.css
  lib/scss/components/news-list-item/_list-item.scss
Labels: frontend, size/xs

#86 D8CORE-2228: adding the nav tag so we get a landmarks menu in voiceover.
  templates/block/block--menu-block--news-topics.html.twig
Labels: frontend, size/xs
