Repository SU-SWS/stanford_news, pull requests merged in 2020-07, with the labels that each got.

#89 D8CORE-2178, D8CORE-2180, D8CORE-2181: Event updates
  config/install/core.entity_form_display.node.stanford_news.default.yml
  config/install/field.field.node.stanford_news.su_news_publishing_date.yml
  config/install/field.field.node.stanford_news.su_news_topics.yml
  config/install/views.view.stanford_news.yml
Labels: size/xs

#90 "8.x-2.x > 8.2.3
  CHANGELOG.md
  composer.json
  config/install/core.entity_form_display.node.stanford_news.default.yml
  config/install/field.field.node.stanford_news.su_news_publishing_date.yml
  config/install/field.field.node.stanford_news.su_news_topics.yml
  config/install/views.view.stanford_news.yml
  dist/css/news-list-item.css
  dist/css/news-vertical-teaser.css
  lib/scss/components/news-list-item/_list-item.scss
  lib/scss/components/news-vertical-teaser/_news-vertical-teaser.scss
  stanford_news.info.yml
  templates/block/block--menu-block--news-topics.html.twig
Labels: frontend, patch, size/xs

#91 Removed views_taxonomy_term_name_depth thats not used
  composer.json
  stanford_news.info.yml
Labels: size/xs

#92 D8CORE-1938: on vertical cards, move focus indicator from link/image …
  dist/css/news-vertical-teaser.css
  lib/scss/components/news-vertical-teaser/_news-vertical-teaser.scss
Labels: frontend, size/xs

#93 D8CORE-2132: adding a wrapper div to address issue with SOE subtheme
  templates/components/news-vertical-teaser/news-vertical-teaser.twig
Labels: frontend, size/xs
