Repository SU-SWS/stanford_news, pull requests merged in 2021-02, with the labels that each got.

#114 D8CORE-3105: fixing for the no image and external link on a news
  dist/css/news-list-item.css
  dist/css/news-node.css
  dist/css/news-vertical-teaser.css
  lib/scss/components/news-vertical-teaser/_news-vertical-teaser.scss
Labels: frontend, size/xs

#115 "8.x-2.x 8.2.9
  .circleci/config.yml
  CHANGELOG.md
  composer.json
  dist/css/news-list-item.css
  dist/css/news-node.css
  dist/css/news-vertical-teaser.css
  lib/scss/components/news-list-item/_list-item.scss
  lib/scss/components/news-vertical-teaser/_news-vertical-teaser.scss
  stanford_news.info.yml
  stanford_news.module
  templates/field/field--node--su-news-dek--stanford-news.html.twig
Labels: backend, ci, frontend, patch, size/xs

#116 Updated views taxonomy term name depth patch
  composer.json
Labels: size/xs

#117 "8.x-2.x 8.2.10
  CHANGELOG.md
  composer.json
  stanford_news.info.yml
Labels: patch, size/xs

#118 Moved patches to shared package
  composer.json
  stanford_news.info.yml
Labels: size/xs

#119 D8CORE-3515: fixing news padding for no image
  dist/css/news-vertical-teaser.css
  lib/scss/components/news-vertical-teaser/_news-vertical-teaser.scss
Labels: frontend, size/xs
