Repository SU-SWS/stanford_news, pull requests merged in 2021-09, with the labels that each got.

#131 D8CORE-4643: moving the filter menu to Stanford Basic
  dist/css/news-list-item.css
  dist/js/news-list.behaviors.js
  lib/js/stanford_news_list.behavior.js
  lib/scss/components/filter-menu/_filter-menu.scss
  lib/scss/components/filter-menu/index.scss
  lib/scss/components/news-list-item/index.scss
  stanford_news.module
  templates/block/block--menu-block--news-topics.html.twig
Labels: size/s, backend, frontend

#132 D8CORE-3161: Changed the load more button size
  dist/css/news-list-item.css
  lib/scss/components/news-list-item/_list-item.scss
Labels: size/xs, frontend

#133 8.2.15
  CHANGELOG.md
  dist/css/news-list-item.css
  dist/js/news-list.behaviors.js
  lib/js/stanford_news_list.behavior.js
  lib/scss/components/filter-menu/_filter-menu.scss
  lib/scss/components/filter-menu/index.scss
  lib/scss/components/news-list-item/_list-item.scss
  lib/scss/components/news-list-item/index.scss
  stanford_news.info.yml
  stanford_news.module
  templates/block/block--menu-block--news-topics.html.twig
Labels: size/s, patch, backend, frontend

#134 D8CORE-4768: moving this condition back to news
  dist/css/news-list-item.css
  lib/scss/components/news-list-item/_list-item.scss
Labels: size/xs, frontend

#135 8.2.16
  CHANGELOG.md
  dist/css/news-list-item.css
  lib/scss/components/news-list-item/_list-item.scss
  stanford_news.info.yml
Labels: size/xs, patch, frontend
