Repository SU-SWS/stanford_news, pull requests merged in 2021-06, with the labels that each got.

#125 4090 unique
  templates/components/news-list/news-item-list.twig
Labels: frontend, size/xs

#124 D8CORE-4090 D8CORE-2888 D8CORE-4126: Accessibility fixes to the news
  dist/css/news-list-item.css
  lib/scss/components/news-list-item/_list-item.scss
  templates/components/news-list/news-item-list.twig
Labels: frontend, size/s

#126 "8.x-2.x 8.2.13
  .circleci/config.yml
  .github/pull_request_template.md
  CHANGELOG.md
  composer.json
  dist/css/news-list-item.css
  lib/scss/components/news-list-item/_list-item.scss
  stanford_news.info.yml
  templates/components/news-list/news-item-list.twig
Labels: ci, frontend, patch, size/s

#127 D8CORE-4378: adding the skip to secondary link
  templates/block/block--menu-block--news-topics.html.twig
Labels: frontend, size/xs
