Repository SU-SWS/stanford_news, pull requests merged in 2022-03, with the labels that each got.

#141 test on php8
  .circleci/config.yml
Labels: size/xs, ci

#142 D8CORE-4362: fixing the padding after a banner image on the news page.
  dist/css/news-node.css
  dist/js/news-node.behaviors.js
  lib/scss/components/news-node/_news-node.scss
Labels: size/xs, frontend

#143 D8CORE-5568 Fix news list template when no date is available
  templates/components/news-list/news-item-list.twig
Labels: size/xs, frontend

#144 update views infinite scroll
  composer.json
Labels: size/xs

#145 8.2.19
  .circleci/config.yml
  CHANGELOG.md
  composer.json
  dist/css/news-node.css
  dist/js/news-node.behaviors.js
  lib/scss/components/news-node/_news-node.scss
  stanford_news.info.yml
  templates/components/news-list/news-item-list.twig
Labels: size/xs, patch, frontend, ci

#146 D8CORE-5638: removing the extra margin-top on the small size for news cards
  dist/css/news-vertical-teaser.css
  lib/scss/components/news-vertical-teaser/_news-vertical-teaser.scss
Labels: size/xs, frontend
